# Reference only. scripts/install-into-kernel.sh adds this line for you.
#
# To do it by hand, append to arch/arm64/boot/dts/freescale/Makefile next to
# the other i.MX93 entries:

dtb-$(CONFIG_ARCH_MXC) += imx93-11x11-frdm-imx519.dtb
